package com.appzone.cipg.model;


/*<merchant_id> with the ID auto-generated by Fidelity PayGate  for the merchant.
<curr_code> with the appropriate currency code (Naira code = 566, Dollar code = 840, Pound code = 826)
<amount> with the amount of the transaction.
<order_id> with the order id of the transaction.
<product_name> with the product name.
<customer_email> with the customer email.
*/


public class Charge {
    private String amount="";
    private String merchantId = "";
    private String currencyCode = "566";
    private String orderId = "";
    private String customerEmail = "";
    private String productName="";

    public Charge() {

    }

    public Charge(String amount, String merchantId, String currencyCode, String orderId, String productName, String customerEmail) {
        this.amount = amount;
        this.merchantId = merchantId;
        this.currencyCode = currencyCode;
        this.orderId = orderId;
        this.productName = productName;
        this.customerEmail = customerEmail;
    }

    public String getAmount() {
        return amount;
    }

    public void setAmount(String amount) {
        this.amount = amount;
    }

    public String getMerchantId() {
        return merchantId;
    }

    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId;
    }

    public String getCurrencyCode() {
        return currencyCode;
    }

    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    public String getCustomerEmail() {
        return customerEmail;
    }

    public void setCustomerEmail(String customerEmail) {
        this.customerEmail = customerEmail;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }
}
